name: KindMaster
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: apparmor
      run: |
        set -x
        sudo aa-status
        ls -l /etc/apparmor.d
        sudo cat /etc/apparmor.d/usr.sbin.mysqld
        sudo rm -rf /etc/apparmor.d/usr.sbin.mysqld
        sudo systemctl restart apparmor
        sudo systemctl status apparmor 
        sudo aa-status

    - name: Create Cluster
      run: |
        set -x
        # echo 'options overlay metacopy=off redirect_dir=off' > /tmp/overlay.conf
        # sudo mv /tmp/overlay.conf /etc/modprobe.d/disable_overlay_redirect_dir.conf
        sudo systemctl restart docker
        export GOPATH=$(go env GOPATH)
        export GOBIN=${GOPATH}/bin
        GO111MODULE=on go get sigs.k8s.io/kind@master
        # mkdir -p ${GOPATH}/src/sigs.k8s.io
        # cd ${GOPATH}/src/sigs.k8s.io
        # git clone https://github.com/BenTheElder/kind.git
        # cd kind
        # git checkout unarmored
        # GO111MODULE=on go install ./...
        sudo mv ${GOBIN}/kind /usr/local/bin/kind
        kind version
        kind create cluster
        echo "waiting for nodes to be ready ..."
        kubectl wait --for=condition=Ready nodes --all --timeout=5m
        kubectl get nodes
        kubectl wait --for=condition=Ready pods -n local-path-storage --all --timeout=5m
        kubectl get pods --all-namespaces

    - name: Run e2e tests
      run: |
        uname -a
        docker info
        id
        ls -l /etc/mysql/conf.d/
        echo "run mysql"
        kubectl apply -f hack/kubernetes/mysql.yaml
        sleep 10
        # kubectl wait --for=condition=Ready pods stash-e2e --timeout=5m
        kubectl describe pod stash-e2e
        sleep 10
        kubectl describe pod stash-e2e
        sleep 10
        kubectl describe pod stash-e2e
        sleep 10
        kubectl describe pod stash-e2e
        sleep 10
        kubectl describe pod stash-e2e
        sleep 10
        kubectl describe pod stash-e2e
        echo ________________________________________________________-        
        kubectl logs -f stash-e2e &
        sleep 60
